name: build

on:
  push:
    branches:
      - main

jobs:
  run-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      
      - name: install-nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install-dependencies
        run: npm install
      
      - name: build-project
        run: npm run build
      
      - name: deploy-to-github-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build'
